services:
  
  my_postgres_db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_fazenda
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
  
  django_web:
    build: .
    command: sh -c "sleep 5 && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 setup.wsgi"
    # command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 setup.wsgi
    tty: true  # Mantém o contêiner ativo
    ports:
      - "8000:8000"
    depends_on:
      - my_postgres_db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_db_data:
