# Generated by Django 5.2.1 on 2025-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        help_text="CPF (11 digits) or CNPJ (14 digits)",
                        max_length=14,
                        unique=True,
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
                "ordering": ["name"],
            },
        ),
    ]
